// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package types

type CreateOrderReq struct {
	CustomerName string  `json:"customer_name" validate:"required,min=2,max=50"`
	Email        string  `json:"email" validate:"required,email"`
	ProductCode  string  `json:"product_code" validate:"required"`
	Quantity     int64   `json:"quantity" validate:"required,gte=1,lte=100"`
	Amount       float64 `json:"amount" validate:"required,gt=0"`
}

type CreateOrderResp struct {
	OrderId string `json:"order_id"`
	Status  string `json:"status"`
	Message string `json:"message"`
}

type GetOrderReq struct {
	OrderId string `path:"order_id"`
}

type GetOrderResp struct {
	OrderId      string  `json:"order_id"`
	CustomerName string  `json:"customer_name"`
	ProductCode  string  `json:"product_code"`
	Quantity     int64   `json:"quantity"`
	Amount       float64 `json:"amount"`
	Status       string  `json:"status"`
}
