# Stage 1: Build binary for payment-rpc
FROM golang:1.24-alpine AS builder

WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o payment-rpc rpc/payment/payment.go

# Stage 2: Final runner
FROM alpine:latest

WORKDIR /app
RUN apk --no-cache add ca-certificates tzdata
COPY --from=builder /app/payment-rpc /app/payment-rpc
COPY --from=builder /app/rpc/payment/etc /app/etc

EXPOSE 8088
CMD ["./payment-rpc", "-f", "etc/payment.yaml"]
