// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: payment.proto

package server

import (
	"context"

	"order-hub/rpc/payment/internal/logic/payment"
	"order-hub/rpc/payment/internal/svc"
	"order-hub/rpc/payment/payment"
)

type PaymentServer struct {
	svcCtx *svc.ServiceContext
	payment.UnimplementedPaymentServer
}

func NewPaymentServer(svcCtx *svc.ServiceContext) *PaymentServer {
	return &PaymentServer{
		svcCtx: svcCtx,
	}
}

func (s *PaymentServer) ProcessPayment(ctx context.Context, in *payment.ProcessPaymentReq) (*payment.ProcessPaymentResp, error) {
	l := paymentlogic.NewProcessPaymentLogic(ctx, s.svcCtx)
	return l.ProcessPayment(in)
}
