// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2
// Source: payment.proto

package payment

import (
	"context"

	"order-hub/rpc/payment/payment"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	ProcessPaymentReq  = payment.ProcessPaymentReq
	ProcessPaymentResp = payment.ProcessPaymentResp

	Payment interface {
		ProcessPayment(ctx context.Context, in *ProcessPaymentReq, opts ...grpc.CallOption) (*ProcessPaymentResp, error)
	}

	defaultPayment struct {
		cli zrpc.Client
	}
)

func NewPayment(cli zrpc.Client) Payment {
	return &defaultPayment{
		cli: cli,
	}
}

func (m *defaultPayment) ProcessPayment(ctx context.Context, in *ProcessPaymentReq, opts ...grpc.CallOption) (*ProcessPaymentResp, error) {
	client := payment.NewPaymentClient(m.cli.Conn())
	return client.ProcessPayment(ctx, in, opts...)
}
