// Code generated by goctl. DO NOT EDIT.
// goctl 1.10.2

package handler

import (
	"net/http"

	"order-hub/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.AuditLog},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/orders",
					Handler: CreateOrderHandler(serverCtx),
				},
				{
					Method:  http.MethodGet,
					Path:    "/orders/:order_id",
					Handler: GetOrderHandler(serverCtx),
				},
			}...,
		),
		rest.WithPrefix("/api/v1"),
	)
}
